export const FIELDS_ORDER = [
  "sku",
  "type",
  "roadHazardWarranty",
  "loadRange",
  "speedRating",
  "performance",
  "mpn",
  "overallDiameter",
  "season",
  "aspectRatio",
  "utqg",
  "runFlat",
  "rebateAvailable",
  "countryOfOrigin",
  "sidewall",
  "size",
  "loadIndex",
  "sectionWidth",
  "rimDiameter",
  "treadDepth",
];

export const FIELD_LABELS: { [key: string]: string } = {
  sku: "SKU",
  type: "Type",
  roadHazardWarranty: "Road Hazard Warranty",
  loadRange: "Load Range",
  speedRating: "Speed Rating",
  performance: "Performance",
  mpn: "MPN",
  overallDiameter: "Overall Diameter",
  season: "Season",
  aspectRatio: "Aspect Ratio",
  utqg: "UTQG",
  runFlat: "Run Flat",
  rebateAvailable: "Rebate Available",
  countryOfOrigin: "Country of Origin",
  sidewall: "Sidewall",
  size: "Size",
  loadIndex: "Load Index",
  sectionWidth: "Section Width",
  rimDiameter: "Rim Diameter",
  treadDepth: "Tread Depth",
};
